openapi: 3.0.0
servers:
  - url: "https://{env}-sg.portal.hocvienconggiao.com"
    variables:
      env:
        enum:
          - dev
          - prod
        default: dev

info:
  version: 0.1.0
  title: OpenAPI person info
  license:
    name: Apache-2.0
    url: "https://www.apache.org/licenses/LICENSE-2.0.html"
tags:
  - name: person
    description: Everything about your persons
paths:
  /mutation-api/person-service/persons:
    post:
      tags:
        - person-mutation
      summary: Create a new person
      operationId: addPerson
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PersonUpsert"
        "405":
          description: Invalid input
      requestBody:
        $ref: "#/components/requestBodies/PersonRequest"
      security:
        - person_auth: []

externalDocs:
  description: Find out more about Swagger
  url: "http://swagger.io"
components:
  requestBodies:
    PersonArray:
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: "#/components/schemas/PersonUpsert"
      description: List of person object
      required: true
    PersonRequest:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/PersonUpsert"
      description: person object that needs to be added to the database
      required: true
  securitySchemes:
    person_auth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    IdNumberProvider:
      type: string
      enum:
        - NATIONAL_ID
        - PASSPORT
    Nationality:
      type: string
      enum:
        - VIETNAMESE
        - CHINESE
        - BRITISH
        - AMERICAN
        - FRENCH
    Language:
      type: string
      enum:
        - VIETNAMESE
        - CHINESE
        - BRITISH
        - AMERICAN
        - FRENCH
        - ENGLISH
    PersonalIdNumber:
      title: Personal ID number
      type: object
      properties:
        idNumber:
          type: string
          example: 099005014120
        idNumberProvider:
          $ref: "#/components/schemas/IdNumberProvider"
        dateOfIssue:
          type: string
          format: date
        placeOfIssue:
          type: string
    CompletedProgram:
      title: Completed the proram
      type: string
      enum:
        - ELEMENTARY_SCHOOL
        - MIDDLE_SCHOOL
        - HIGH_SCHOOL
        - BACHELOR
        - MASTER
        - DOCTOR
        - OTHER
      example: OTHER
    Position:
      title: Position
      type: object
      properties: 
        pastor:
          type: object
          properties:
            diocese:
              type: string
              example: Xuan loc
            order:
              type: string
              example: Da minh
        seminarian:
          type: object
          properties:
            diocese:
              type: string
              example: Xuan loc
            order:
              type: string
              example: Da minh
        monk:
          type: string
          enum: 
           - SOLEMN_VOW # khấn trọn
           - SIMPLE_VOW # khấn tạm
           - NOVICE # dự tu
           - PREPARATION # nhà tập
        parishioner:
          type: object
          properties:
            diocese:
              type: string
              example: Xuan loc
            parish:
              type: string
              example: Doc mo
    Program:
      type: string
      enum:
        - BACHELOR #Cử nhân
        - YEAR_OF_PREPARATION_DOCMATIC #năm chuẩn bị tín lý
        - YEAR_OF_PREPARATION_SCRIPTURES #năm chuẩn bị kinh thánh
        - MASTER_THEOLOGY_DOGMATIC # thạc sĩ thần học tín lý
        - MASTER_THEOLOGY_SCRIPTURES # thạc sĩ thần học kinh thánh
        - MASTER_OF_ARTS_IN_MINISTRY # thạc sĩ mục vụ
    
    PersonUpsert:
      title: PersonUpsert
      description: Person info
      type: object
      properties:
        firstName:
          type: string
          example: Chien
        middleName:
          type: string
          example: Huu
        lastName:
          type: string
          example: Nguyen
        saintName:
          type: string
          example: Giuse
        dateOfBirth:
          type: string
          format: date
          example: 1983-05-16
          description: date of birth in format YYYY-MM-DD
        placeOfBirth:
          type: string
          example: Tra Vinh
        email:
          type: string
          example: binh@sunrise.vn
        phone:
          type: string
          example: +84 1228019700
        address:
          type: string
          example: 1000 CMT8 p5 q.Tân Bình, TP.HCM
        nationality:
          $ref: "#/components/schemas/Nationality"
        race:
          type: string
          example: Kinh
        personalIdNumbers:
          type: array
          items:
            $ref: "#/components/schemas/PersonalIdNumber"
        language: 
          $ref: '#/components/schemas/Language'
        completedProgram:
          $ref: "#/components/schemas/CompletedProgram"
        position:
          $ref: '#/components/schemas/Position'
        program:
          $ref: '#/components/schemas/Program'
      xml:
        name: person

    PersonView:
      title: PersonView
      description: Person View
      type: object
      required:
        - id
      properties:
        id:
          type: string
          format: uuid
          example: 53f549b9-99bf-4e12-88e3-c2f868953283
        name:
          type: string
          example: Nguyen Huu Chien
        dateOfBirth:
          type: string
          format: date
          example: 1983-05-16
          description: date of birth in format YYYY-MM-DD
        placeOfBirth:
          type: string
          example: Tra Vinh
        email:
          type: string
          example: binh@sunrise.vn
        phone:
          type: string
          example: +84 1228019700
        personalIdNumbers:
          type: array
          items:
            $ref: "#/components/schemas/PersonalIdNumber"

      xml:
        name: person-view
    PersonViewCollection:
      required:
        - persons
      properties:
        persons:
          type: array
          items:
            $ref: "#/components/schemas/PersonView"
        hasMore:
          type: boolean
        total:
          type: integer
          format: int64

security:
  - person_auth: []