openapi: 3.0.0
servers:
  - url: 'http://{env}-sg.portal.hocvienconggiao.com'
    variables:
      env:
        enum:
          - dev
          - prod
        default: dev
  
info:
  description: >-
    This is a API for identity.
  version: 0.3.1
  title: OpenAPI Indentity info
  license:
    name: Apache-2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: users
    description: Everything about users
paths:
  /query-api/user/:
    get:
      tags:
        - query-user
      summary: Get users infomation
      description: Returns a single user
      operationId: query-user
      parameters:
        - in: query
          name: id
          schema:
            type: string
          description: The user id
        - in: query
          name: userName
          schema:
            type: string
          description: The user name
        - in: query
          name: phone
          schema:
            type: string
          description: The userphone number
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Invalid ID supplied
        '404':
          description: User not found
  /mutation-api/user/update-password:
    post:
      tags:
        - mutation-user
      summary: update password
      description: ''
      operationId: updatePassword
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                plainPassword:
                  type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '405':
          description: Invalid input
      security:
        - user_auth: [ ]
externalDocs:
  description: Find out more about Swagger
  url: 'http://swagger.io'
components:
  securitySchemes:
    user_auth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    User:
      title: User
      description: User info
      type: object
      required:
        - id
        - userName
        - email
        - password
      properties:
        id:
          type: string
          format: uuid        
        userName:
          type: string
        email:
          type: string
        phone:
          type: string
        password:
          type: string

security:
  - user_auth: []
