openapi: 3.0.0
servers:
  - url: 'https://{env}-sg.portal.hocvienconggiao.com'
    variables:
      env:
        enum:
          - dev
          - prod
        default: dev

info:
  description: >-
    This is a server for Catholic Polity info.
  version: 0.2.0
  title: OpenAPI Catholic Polity info
  license:
    name: Apache-2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: polity
    description: Everything about your Polities
paths:
  /mutation-api/catholic-polity-service/parishes:
    post:
      tags:
        - parish
      summary: Add new parish
      description: ''
      operationId: add_parish
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Parish'
        '405':
          description: Invalid input
      requestBody:
        $ref: '#/components/requestBodies/ParishRequest'
      security:
        - polity_auth: []
  /mutation-api/catholic-polity-service/dioceses:
    post:
      tags:
        - diocese
      summary: Add new diocese
      description: ''
      operationId: add_diocese
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Diocese'
        '405':
          description: Invalid input
      requestBody:
        $ref: '#/components/requestBodies/DioceseRequest'
      security:
        - polity_auth: []
  /mutation-api/catholic-polity-service/deaneries:
    post:
      tags:
        - deanery
      summary: Add new deanery
      description: ''
      operationId: add_deanery
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Deanery'
        '405':
          description: Invalid input
      requestBody:
        $ref: '#/components/requestBodies/DeaneryRequest'
      security:
        - polity_auth: []
  /query-api/catholic-polity-service/parishes:
    get:
      tags:
        - parish
      summary: Get all parishes
      description: Returns all parishes
      operationId: get_parishes
      parameters:
        - in: query
          name: dioceseName
          schema:
            type: string
        - in: query
          name: dioceseId
          schema:
            type: string 
            format: uuid
        - in: query
          name: name
          schema:
            type: string
        - in: query
          name: offset
          schema:
            type: integer
            minimum: 0
          required: false
          description: The number of parishes to skip before starting to collect the result set.
        - in: query
          name: count
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 20
          required: false
          description: The number of parishes to return.
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ParishCollection'
        '400':
          description: Invalid ID supplied
        '404':
          description: Parish not found
  /query-api/catholic-polity-service/dioceses:
    get:
      tags:
        - diocese
      summary: Get all dioceses
      description: Returns all dioceses
      operationId: get_dioceses
      parameters:
        - in: query
          name: provinceName
          schema:
            type: string          
        - in: query
          name: name
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DioceseCollection'
        '400':
          description: Invalid ID supplied
        '404':
          description: Diocese not found
  /query-api/catholic-polity-service/deaneries:
    get:
      tags:
        - deanery
      summary: Get deaneries
      description: Returns all deaneries
      operationId: get_deaneries
      parameters:
        - in: query
          name: provinceName
          schema:
            type: string          
        - in: query
          name: name
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeaneryCollection'
        '400':
          description: Invalid ID supplied
        '404':
          description: Deanery not found
  /query-api/catholic-polity-service/parishes/{id}:
    get:
      tags:
        - parish
      summary: Find parish by ID
      description: Returns a single parish
      operationId: get_parish_by_id
      parameters:
        - name: id
          in: path
          description: ID of parish to return
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Parish'
        '400':
          description: Invalid ID supplied
        '404':
          description: Parish not found
  /query-api/catholic-polity-service/dioceses/{id}:
    get:
      tags:
        - diocese
      summary: Find diocese by ID
      description: Returns a single diocese
      operationId: get_diocese_by_id
      parameters:
        - name: id
          in: path
          description: ID of diocese to return
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Diocese'
        '400':
          description: Invalid ID supplied
        '404':
          description: Diocese not found
  /query-api/catholic-polity-service/deaneries/{id}:
    get:
      tags:
        - deanery
      summary: Find deanery by ID
      description: Returns a single deanery
      operationId: get_deanery_by_id
      parameters:
        - name: id
          in: path
          description: ID of deanery to return
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Deanery'
        '400':
          description: Invalid ID supplied
        '404':
          description: Deanery not found
  /mutation-api/catholic-polity-service/parish/{id}:
    put:
      tags:
        - parish
      summary: Update an existing parish
      operationId: update_parish
      parameters:
        - name: id
          in: path
          description: ID of parish to update
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Parish'
        '400':
          description: Invalid ID supplied
        '404':
          description: Parish not found
        '405':
          description: Validation exception
      requestBody:
        $ref: '#/components/requestBodies/ParishRequest'
      security:
        - polity_auth: []
    delete:
      tags:
        - parish
      summary: "Delete parish by ID"
      operationId: delete_parish
      parameters:
        - name: id
          in: path
          description: ID of parish to delete
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: successful operation
        '400':
          description: Invalid ID supplied
        '404':
          description: Parish not found
      security:
        - polity_auth: []
  /mutation-api/catholic-polity-service/deanery/{id}:
    put:
      tags:
        - deanery
      summary: Update an existing deanery
      description: ''
      operationId: update_deanery
      parameters:
        - name: id
          in: path
          description: ID of deanery to update
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Deanery'
        '400':
          description: Invalid ID supplied
        '404':
          description: Deanery not found
        '405':
          description: Validation exception
      requestBody:
        $ref: '#/components/requestBodies/DeaneryRequest'
      security:
        - polity_auth: []
    delete:
      tags:
        - deanery
      summary: "Delete deanery by ID"
      operationId: delete_deanery
      parameters:
        - name: id
          in: path
          description: ID of deanery to delete
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: successful operation
        '400':
          description: Invalid ID supplied
        '404':
          description: Deanery not found
      security:
        - polity_auth: []
  /mutation-api/catholic-polity-service/diocese/{id}:
    put:
      tags:
        - diocese
      summary: Update an existing diocese
      description: ''
      operationId: update_diocese
      parameters:
        - name: id
          in: path
          description: ID of diocese to update
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Diocese'
        '400':
          description: Invalid ID supplied
        '404':
          description: Diocese not found
        '405':
          description: Validation exception
      requestBody:
        $ref: '#/components/requestBodies/DioceseRequest'
      security:
        - polity_auth: []
    delete:
      tags:
        - diocese
      summary: "Delete diocese by ID"
      operationId: delete_diocese
      parameters:
        - name: id
          in: path
          description: ID of diocese to delete
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: successful operation
        '400':
          description: Invalid ID supplied
        '404':
          description: Diocese not found
      security:
        - polity_auth: []
externalDocs:
  description: Find out more about Swagger
  url: 'http://swagger.io'
components:
  requestBodies:
    ParishArray:
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Parish'
      description: List of parishes object
      required: true
    ParishRequest:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Parish'
    DeaneryArray:
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Deanery'
      description: List of deaneries object
      required: true
    DeaneryRequest:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Deanery'
      description: Parish object that needs to be added to the database
      required: true
    DioceseArray:
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Diocese'
      description: List of dioceses object
      required: true
    DioceseRequest:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Diocese'
      description: Diocese object that needs to be added to the database
      required: true
  securitySchemes:
    polity_auth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    EcclesiasticalProvince:
      type: string
      enum:
        - HA_NOI
        - HUE
        - SAI_GON
    Polity:
      type: object
      required:
        - "name"
        - "personInCharge"
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        personInCharge:
           type: string
    Diocese:
      allOf:
        - $ref: "#/components/schemas/Polity"
      type: object
      description: An area controlled by a ecclesiastical province
      required:
        - "ecclesiasticalProvince"
      properties:
        ecclesiasticalProvince:
          $ref: "#/components/schemas/EcclesiasticalProvince"
    Deanery:
      allOf:
        - $ref: "#/components/schemas/Polity"
      type: object
      description: An area controlled by a diocese
      required:
        - "diocese"
      properties:
        diocese:
          $ref: "#/components/schemas/Diocese"
    Parish:
      allOf:
        - $ref: "#/components/schemas/Polity"
      type: object
      required:
        - "deanery"
        - "name"
      properties:
        name:
          type: string
        deanery:
          $ref: "#/components/schemas/Deanery"
    DioceseCollection:
      properties:
        dioceses:
          type: array
          items:
            $ref: '#/components/schemas/Diocese'
    DeaneryCollection:
      properties:
        deaneries:
          type: array
          items:
            $ref: '#/components/schemas/Deanery'
    ParishCollection:
      properties:
        parishes:
          type: array
          items:
            $ref: '#/components/schemas/Parish'
        hasMore:
          type: boolean

security:
  - polity_auth: []
