openapi: 3.0.0
servers:
  - url: 'http://{env}-sg.portal.hocvienconggiao.com'
    variables:
      env:
        enum:
          - dev
          - prod
        default: dev

info:
  description: >-
    This is a server for Catholic Polity info.
  version: 0.1.0
  title: OpenAPI Catholic Polity info
  license:
    name: Apache-2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: polity
    description: Everything about your Polities
paths:
  /mutation-api/polity:
    post:
      tags:
        - polity
      summary: Add new polity
      description: ''
      operationId: addPolity
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Polity'
        '405':
          description: Invalid input
      requestBody:
        $ref: '#/components/requestBodies/PolityRequest'
      security:
        - polity_auth: []
  /query-api/polity:
    get:
      tags:
        - polity
      summary: Get all polities
      description: Returns all polities
      operationId: getAllPolities
      parameters:
        - in: query
          name: province
          schema:
            $ref: '#/components/schemas/EcclesiasticalProvince'
        - in: query
          name: diocese
          schema:
            type: string
        - in: query
          name: parish
          schema:
            type: string
        - in: query
          name: offset
          schema:
            format: uuid
            type: string
          required: false
          description: The number of polities to skip before starting to collect the result set.
        - in: query
          name: count
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 20
          required: false
          description: The number of polities to return.
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Polity'
        '400':
          description: Invalid ID supplied
        '404':
          description: Catholic Polity not found
  /query-api/polity/{id}:
    get:
      tags:
        - polity
      summary: Find polity by ID
      description: Returns a single polity
      operationId: getPolityById
      parameters:
        - name: id
          in: path
          description: ID of polity to return
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Polity'
        '400':
          description: Invalid ID supplied
        '404':
          description: Catholic Polity not found
  /mutation-api/polity/{id}:
    put:
      tags:
        - polity
      summary: Update an existing polity
      description: ''
      operationId: updatePolity
      parameters:
        - name: id
          in: path
          description: ID of polity to update
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Polity'
        '400':
          description: Invalid ID supplied
        '404':
          description: Catholic Polity not found
        '405':
          description: Validation exception
      requestBody:
        $ref: '#/components/requestBodies/PolityRequest'
      security:
        - polity_auth: []
    delete:
      tags:
        - polity
      summary: "Delete Catholic polity by ID"
      operationId: deletePolity
      parameters:
        - name: id
          in: path
          description: "ID of Catholic polity that needs to be deleted"
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '400':
          description: Invalid polity value
      security:
        - polity_auth: []
externalDocs:
  description: Find out more about Swagger
  url: 'http://swagger.io'
components:
  requestBodies:
    PolityArray:
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Polity'
      description: List of polity object
      required: true
    PolityRequest:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Polity'
      description: Catholic Polity object that needs to be added to the database
      required: true
  securitySchemes:
    polity_auth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    EcclesiasticalProvince:
      type: string
      enum:
        - HA NOI
        - HUE
        - SAI GON
    Polity:
      type: object
      required:
        - "diocese"
        - "ecclesiasticalProvince"
        - "parish"
      properties:
        id:
          type: string
          format: uuid
        ecclesiasticalProvince:
          $ref: "#/components/schemas/EcclesiasticalProvince"
        diocese:
          type: string
          example: Ho Chi Minh
          description: An area controlled by a ecclesiastical province
        parish:
          type: string
          example: Hoa Hung

security:
  - polity_auth: []