name: Build and Push

on:
  push:
    branches:
      - feature/convert_to_github_action
jobs:
  generate_crate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Setup java
        uses: actions/setup-java@v2
        with:
          java-version: 1.8
      - name: Check java
        run:
          java --version
