name: Build and Push

on:
  push:
    branches:
      - feature/convert_to_github_action
jobs:
  generate_crate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Setup java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Check java version
        run: java --version
      - name: Create rust-openapi folder
        run: mkdir -p rust-openapi/.cargo
      - name: Generate Rust sources
        run: |
          files=`git diff-tree --no-commit-id --name-only -r HEAD`
          for file in $files; do
          if [[ $file == contracts* ]]; then
          filename=$(basename $file)
          entity_name=${filename%.*}
          echo "Entity NAME is " + $entity_name
          echo "yes";
          bounded_context=$(basename $(dirname $(dirname $file)))
          echo "Bounded Context name is " + $bounded_context
           java -jar ./bin/openapi-generator-cli.jar generate -i ./contracts/${bounded_context}/openapi/${entity_name}.yaml -g rust-server -o rust-openapi/${bounded_context}_openapi_$entity_name --package-name=hvcg_${bounded_context}_openapi_${entity_name} -c ./bin/config.yaml --type-mappings=date=NaiveDate
          fi
          done
      - name: Verify result
        run: pwd && ls -l rust-openapi

