name: Build and Push

on:
  push:
    branches:
      - main
jobs:
  generate_crate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Setup java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Check java version
        run: java --version
      - name: Create rust-openapi folder
        run: mkdir -p rust-openapi/.cargo
      - name: Generate Rust sources
        run: |
          files=`git diff-tree --no-commit-id --name-only -r HEAD`
          for file in $files; do
          if [[ $file == contracts* ]]; then
          filename=$(basename $file)
          entity_name=${filename%.*}
          echo "Entity NAME is " + $entity_name
          echo "yes";
          bounded_context=$(basename $(dirname $(dirname $file)))
          echo "Bounded Context name is " + $bounded_context
           java -jar ./bin/openapi-generator-cli.jar generate -i ./contracts/${bounded_context}/openapi/${entity_name}.yaml -g rust-server -o rust-openapi/${bounded_context}_openapi_$entity_name --package-name=hvcg_${bounded_context}_openapi_${entity_name} -c ./bin/config.yaml --type-mappings=date=NaiveDate
          fi
          done
      - name: Verify result
        run: ls -l /home/runner/work/hvcg-contracts/hvcg-contracts/rust-openapi
      - name: Build dynamic contracts
        run: "
           echo '
             [
               {
                 \"url\": \"/contracts/biography/openapi/saint.yaml\",
                 \"name\": \"biography/saint.yaml\"
               },
               {
                \"url\": \"/contracts/example/openapi/entity.yaml\",
                \"name\": \"example/entity.yaml\"
               },
               {
                \"url\": \"/contracts/iam/openapi/identity.yaml\",
                \"name\": \"iam/identity.yaml\"
               },
               {
                \"url\": \"/contracts/academics/openapi/student.yaml\",
                \"name\": \"academics/student.yaml\"
               },
               {
                \"url\": \"/contracts/enrolable/openapi/enrolable.yaml\",
                \"name\": \"enrolable/enrolable.yaml\"
               }
             ]
           ' >> contracts.json
           && cp ./contracts.json ./contracts/contracts.json
           "
      - name: Copy folder to swaggerui
        run: cp -R ./contracts ./swaggerui/
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1
      - name: Deploy to S3
        run: aws s3 sync ./swaggerui s3://swaggerui.hocvienconggiao.com
